### ISSUE TITLE
How to map `pathway` information to CBD standard?

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/rinse-pathways-checklist#3]
In the checklist, the following columns describe the pathway of introduction:

- pathway: 
  * import_release
  * import_escape
  * import_dispersal (i.e. merging categories ‘corridor’ and ‘unaided’)
  * import_accidental (i.e. merging categories ‘contaminant’ and ‘stowaway’) 

- vector:
  * ornamental (e.g. horticulture)
  * leisure (e.g. hunting, recreational angling)
  * industry (e.g. agriculture, aquaculture, fur farming)
  * biocontrol 
  * research

Thus, 4 x 5 = 20 pathway x vector combinations occur in the raw data

With respect to the pathway columns, these can easily be mapped to the CBD standard. The difficult thing is to interpret the vector information, which is not easily matched with the CBD standard. An example:

raw dataset | direct match CBD | options for mapping to CBD
--- | --- | --- 
import_release: biocontrol | yes | release_biological_control
import_escape: leisure | no | release_fishery, release_hunting
import_release: industry | no | release_landscape_improvement, release_other
import_dispersal: ornamental | yes | corridor
import_dispersal: ornamental | yes | unaided

For the pathway information I think there's no problem. For the vector information, we have several options:

1. We do not map the vector information
2. We do not map the vector information when we don't have a clear match to the CBD standard
3. We map all vector information by attempting to match it to all possible terms of the CBD standard
4. We map vector information as given in the raw data (using the 5 categories), which will not always match the CBD standard.

Imo, the last option would be the most correct and the easiest way to do. However, in that case, we deviate from our own TrIAS vocabulary, which follows the CBD standard. In case this is a problem, I would prefer option 2.

**Comment by qgroom** [comment]
It would be nice to see a whole mapping of one to the other.
I don't understand some things in your table. Is import_release: ornamental mapped to release_biological_control, because if it is then this is not right.
Also, import_dispersal: ornamental doesn't make any sense. import_dispersal by definition is unaided and therefore doesn't have a human vector.

**Comment by LienReyserhove** [comment]
yes, sorry,` import_release: ornamental` should be `import_release: biocontrol` in this example, I corrected this. 
Concerning `dispersal` in this checklist, it is defined as the combination between the CBD categories `unaided` and `corridor`. Indeed, these are unintentional introductions. What the authors see under the vector `ornamental` is less clear (i.e. not clearly defined). They define `vector ` in general as 

> any means that allows the entry or spread of […] alien species” (FAO 2007)

so this shouldn't be introduction by humans per se, but in case of `ornamental`, I wonder what this would be then... dispersal:ornamental has more then 200 records though.

I will make a full overview of all combinations, and how it would potentially match with the CBD standard.

**Comment by qgroom** [comment]
I suppose ornamental really mean horticulture (the industry). Plants are introduced as contaminants to other plants, which means they were imported accidentally through the vector of the horticulture industry. However, these should be mapped to `Contaminant nursery material`.

**Comment by LienReyserhove** [comment]
Here an overview of all combinations of `pathway `+ `vector `, with an interpretation of how I should map it to the CBD standard, the total amount of records (n) and two species as an example (for the group, not for these specific species!).
I need to stress that this is how I should interpret it, but not all CBD subcategories are that clear to me.

My general conclusion: mapping to the CBD subcategories strongly adds to the complexity of the checklist. We should use the six broad categories instead

### Pathway = ACCIDENTAL

Maps to CBD categories STOWAWAY and CONTAMINANT

**vector**: | biocontrol | industry | leisure | ornamental | research
--- | --- | --- | --- | --- | --- |
n | 0 | 12 | 5 | 8 | 1
**species** | | Ambrosia artemisiifolia | Mercenaria mercenaria | Ambrosia artemisiifolia | Pimephales promelas
 | | | Crassostrea gigas | Gymnocephalus cernuus | Bellamya chinensis | |
**category : subcategory** | | contaminant:animal  | contaminant:bait | contaminant: animals | ? 
 | | | contaminant: parasites | contaminant:food | contaminant: plants |
 | | | contaminant: plants | contaminant:animal | |
 | | | contaminant: seed | stowaway:angling | |
 | | | contaminant: timber | stowaway: people luggage | |
 | | | stowaway:machinery | stowaway: vehicles | |
 | | | stowaway:vehicles | | | 

### Pathway = DISPERSAL

Maps to CBD categories CORRIDOR + UNAIDED

**vector**: | biocontrol | industry | leisure | ornamental | research
--- | --- | --- | --- | --- | --- |
n | 11 | 35 | 14 | 45 | 4
**species** | Arundo donax | Acacia mearnsii | Mercenaria mercenaria | Acacia saligna | Branta canadensis 
| | Carpobrotus edulis | Acacia saligna | Acipenser baerii | Ailanthus altissima |  Branta hutchinsii
**category : subcategory** | ? | corridor: tunnels landbridges | corridor: tunnels landbridges | ? | ? |
 | | | corridor: interconnected waterways | corridor: interconnected waterways | | |

### Pathway = ESCAPE

**vector**: | biocontrol | industry | leisure | ornamental | research
--- | --- | --- | --- | --- | --- | 
n | 5 | 45 | 30 | 120 | 23
**species** | Arundo donax | Arundo donax | Mercenaria mercenaria | Arundo donax | Crassostrea rhizophorae
| | Lonicera japonica | Cabomba caroliniana | Acipenser baerii | Buddleja davidii | Clarias gariepinus
**category : subcategory** | escape: other | escape: aquaculture/mariculture | escape: live food and live bait | ecape: botanical garden | escape: other
 | | | escape: agriculture | | escape: pet aquarium/terrarium |
| | | escape: farmed animals | | escape: horticulture |
| | | escape: forestry | |  escape: other |
| | | escape: fur farms | |

### Pathway = RELEASE

**vector**: | biocontrol | industry | leisure | ornamental | research
--- | --- | --- | --- | --- | --- | 
n | 14 | 73 | 45 | 109 |
**species** |  Acacia dealbata  | Acacia dealbata | Mercenaria mercenaria | Acacia dealbata | Crassostrea rhizophorae
| | Arundo donax | Acacia mearnsii  | Acipenser baerii | Acacia saligna  | Clarias gariepinus 
**category : subcategory** | release: biological control | release: fur/transport | release: hunting | release: landscape improvement | release: erosion control
 | | | | release: fishery in the wild | | release: introduction for research purposes

**Comment by qgroom** [comment]
I tried it myself, because it was the only way I could really understand the mapping.
I now understand your four choices better. I suppose I would go for option 2. Though for a few there are one-to-one mappings e.g. pathway:import_release + vector:biocontrol = CBD:Biological control.

It certainly shows the limitations of the CBD vocabulary.


RINSE   pathway: | CBD Category | vector: | CBD Subcategory
-- | -- | -- | --
import_release | RELEASE IN NATURE | ornamental (e.g. horticulture) |  
import_release | RELEASE IN NATURE | leisure (e.g. hunting,   recreational angling) | Fishery in the wild (including   game fishing), Hunting, Landscape/flora/fauna, improvement in the wild, Introduction for conservation purposes or wildlife management
import_release | RELEASE IN NATURE | industry (e.g. agriculture,   aquaculture, fur farming) | Erosion control/ dune   stabilization (windbreaks, hedges, …), Release in nature for use (other than above, e.g., fur, transport, medical use), Other intentional release
import_release | RELEASE IN NATURE | biocontrol | Biological control
import_release | RELEASE IN NATURE | research |  
import_escape | ESCAPE FROM CONFINEMENT | ornamental (e.g. horticulture) | Botanical garden/zoo/aquaria   (excluding domestic aquaria), Pet/aquarium/terrarium species (including live food for such species ), Horticulture, Ornamental purpose other than horticulture
import_escape | ESCAPE FROM CONFINEMENT | leisure (e.g. hunting,   recreational angling) | Live food and live bait
import_escape | ESCAPE FROM CONFINEMENT | industry (e.g. agriculture,   aquaculture, fur farming) | Agriculture (including Biofuel   feedstocks), Aquaculture / mariculture, Farmed animals (including animals left under limited control), Forestry (including afforestation or reforestation), Fur farms
import_escape | ESCAPE FROM CONFINEMENT | biocontrol |  
import_escape | ESCAPE FROM CONFINEMENT | research | Research and ex-situ breeding (in facilities)
import_dispersal   (i.e. merging categories ‘corridor’ and ‘unaided’) | corridor + unaided |   |  
import_dispersal   (i.e. merging categories ‘corridor’ and ‘unaided’) | corridor + unaided |   |  
import_dispersal   (i.e. merging categories ‘corridor’ and ‘unaided’) | corridor + unaided |   |  
import_dispersal   (i.e. merging categories ‘corridor’ and ‘unaided’) | corridor + unaided |   |  
import_dispersal   (i.e. merging categories ‘corridor’ and ‘unaided’) | corridor + unaided |   |  
import_accidental   (i.e. merging categories ‘contaminant’ and ‘stowaway’) | contaminant + stowaway | ornamental (e.g. horticulture) | Contaminant nursery   material     Contaminant on plants (except parasites, species transported by   host/vector)      Parasites on plants (including species transported by host and vector)
import_accidental   (i.e. merging categories ‘contaminant’ and ‘stowaway’) | contaminant + stowaway | leisure (e.g. hunting,   recreational angling) | Contaminated bait
import_accidental   (i.e. merging categories ‘contaminant’ and ‘stowaway’) | contaminant + stowaway | industry (e.g. agriculture,   aquaculture, fur farming) | Food contaminant (including of   live food)     Contaminant on animals (except parasites, species transported by   host/vector)      Parasites on animals (including species transported by host and   vector)     Seed contaminant     Transportation of habitat material (soil, vegetation,…)
import_accidental   (i.e. merging categories ‘contaminant’ and ‘stowaway’) | contaminant + stowaway | biocontrol |  
import_accidental   (i.e. merging categories ‘contaminant’ and ‘stowaway’) | contaminant + stowaway | research |

**Comment by peterdesmet** [comment]
Great work! I would second:

1. Map to one or two level 1 CBD pathways
2. Only map to a level 2 CBD pathway if it is a single one

Based on @qgroom table, it should be rather straightforward to make such a recoding.

**Comment by LienReyserhove** [comment]
Ok, so if I understand it correctly I will go for the conclusion made by @peterdesmet earlier. Thank you all for your input on this puzzle!

**Comment by peterdesmet** [comment]
TODO: document this clearly in Rmd. I'm currently lost on the `vector_provided` and `pathway_provided` values.

**Comment by LienReyserhove** [comment]
See #8 for further discussion
